from flask import Flask, jsonify, request
from flask_cors import CORS
import os
import traceback

# ML model loading utilities
MODEL_PATH = os.path.join(os.path.dirname(__file__), 'models', 'crop_model.pkl')
LABEL_ENCODER_PATH = os.path.join(os.path.dirname(__file__), 'models', 'label_encoder.pkl')

app = Flask(__name__)
CORS(app)

def load_model():
    """
    Try to load a trained model and label encoder. If not present, return None.
    """
    try:
        import joblib
        model = joblib.load(MODEL_PATH)
        le = joblib.load(LABEL_ENCODER_PATH)
        return model, le
    except Exception as e:
        return None, None

@app.route('/')
def index():
    return jsonify(message='ML service - Phase 1')

@app.route('/health')
def health():
    return jsonify(status='ok')

@app.route('/predict_crop', methods=['POST'])
def predict_crop():
    """
    Expects JSON with fields:
      N, P, K, temperature, humidity, ph, rainfall

    If a trained model exists in ml-service/models/crop_model.pkl it will be used.
    If not present, returns 501 with a clear message and instructions to run training.
    """
    try:
        data = request.get_json(silent=True)
        if not data:
            return jsonify(error='No JSON body provided'), 400

        # expected features
        features = ['N','P','K','temperature','humidity','ph','rainfall']
        X = []
        for f in features:
            if f not in data:
                return jsonify(error=f"Missing feature '{f}'"), 400
            try:
                X.append(float(data[f]))
            except ValueError:
                return jsonify(error=f"Feature '{f}' must be numeric"), 400

        model, le = load_model()
        if model is None or le is None:
            return jsonify(
                error='Model not trained',
                message='No trained crop recommendation model found. Please train a model using ml-service/train.py with the appropriate dataset. The ML training and integration structure is present in the repository.'
            ), 501

        import numpy as np
        x_arr = np.array(X).reshape(1, -1)

        # predict
        pred = model.predict(x_arr)
        result_label = le.inverse_transform(pred)[0] if hasattr(le, 'inverse_transform') else str(pred[0])

        # try to get confidence if available
        confidence = None
        if hasattr(model, 'predict_proba'):
            probs = model.predict_proba(x_arr)
            if probs is not None and len(probs.shape) == 2:
                top_idx = probs.argmax(axis=1)[0]
                confidence = float(probs[0][top_idx])

        explanation = 'Recommendation generated by model using input soil and weather features.'

        resp = {
            'recommended_crop': result_label,
            'input': {k: data[k] for k in features},
            'explanation': explanation
        }
        if confidence is not None:
            resp['confidence'] = confidence

        return jsonify(resp)

    except Exception as e:
        traceback.print_exc()
        return jsonify(error='Internal ML service error', details=str(e)), 500

if __name__ == '__main__':
    port = int(os.getenv('ML_SERVICE_PORT', 5001))
    app.run(host='0.0.0.0', port=port, debug=True)
